# Configs the mapping of joints with real devices
# Define the different types of interfaces
types: [ gazebo_position, default]

# Groups for FollowJointTrajectories
groups: { 
 crane: { name: crane, type: default, joints: [crane_first_joint, crane_second_joint, crane_third_joint, crane_fourth_joint, crane_sixth_joint, crane_tip_joint], command_topic: /robospect_platform_controller/command}
}

